compile:
	gcc -I../lib -L../lib -o reader.o reader.c -llogger -Wl,-rpath=../lib/
	gcc -I../lib -L../lib -o writer1.o writer1.c -llogger -Wl,-rpath=../lib/
	gcc -I../lib -L../lib -o writer2.o writer2.c -llogger -Wl,-rpath=../lib/
